//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PlayerSelection.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerSelection: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerSelection()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerSelection"",
    ""maps"": [
        {
            ""name"": ""SelectionAction"",
            ""id"": ""5653d062-a15b-4998-a3ee-3e0a6ecb408d"",
            ""actions"": [
                {
                    ""name"": ""SelectionControls"",
                    ""type"": ""Button"",
                    ""id"": ""8b864eb7-fbeb-40c1-9e01-967282e60fe5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""cfdd621d-a109-46fd-841e-0ca9c283eac5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""628d0602-da17-4ae7-aea4-4deee1d8c5ac"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionControls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a016573-d2ab-457c-98d0-907342294b54"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SelectionAction
        m_SelectionAction = asset.FindActionMap("SelectionAction", throwIfNotFound: true);
        m_SelectionAction_SelectionControls = m_SelectionAction.FindAction("SelectionControls", throwIfNotFound: true);
        m_SelectionAction_PointerPosition = m_SelectionAction.FindAction("PointerPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SelectionAction
    private readonly InputActionMap m_SelectionAction;
    private List<ISelectionActionActions> m_SelectionActionActionsCallbackInterfaces = new List<ISelectionActionActions>();
    private readonly InputAction m_SelectionAction_SelectionControls;
    private readonly InputAction m_SelectionAction_PointerPosition;
    public struct SelectionActionActions
    {
        private @PlayerSelection m_Wrapper;
        public SelectionActionActions(@PlayerSelection wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectionControls => m_Wrapper.m_SelectionAction_SelectionControls;
        public InputAction @PointerPosition => m_Wrapper.m_SelectionAction_PointerPosition;
        public InputActionMap Get() { return m_Wrapper.m_SelectionAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SelectionActionActions set) { return set.Get(); }
        public void AddCallbacks(ISelectionActionActions instance)
        {
            if (instance == null || m_Wrapper.m_SelectionActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SelectionActionActionsCallbackInterfaces.Add(instance);
            @SelectionControls.started += instance.OnSelectionControls;
            @SelectionControls.performed += instance.OnSelectionControls;
            @SelectionControls.canceled += instance.OnSelectionControls;
            @PointerPosition.started += instance.OnPointerPosition;
            @PointerPosition.performed += instance.OnPointerPosition;
            @PointerPosition.canceled += instance.OnPointerPosition;
        }

        private void UnregisterCallbacks(ISelectionActionActions instance)
        {
            @SelectionControls.started -= instance.OnSelectionControls;
            @SelectionControls.performed -= instance.OnSelectionControls;
            @SelectionControls.canceled -= instance.OnSelectionControls;
            @PointerPosition.started -= instance.OnPointerPosition;
            @PointerPosition.performed -= instance.OnPointerPosition;
            @PointerPosition.canceled -= instance.OnPointerPosition;
        }

        public void RemoveCallbacks(ISelectionActionActions instance)
        {
            if (m_Wrapper.m_SelectionActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISelectionActionActions instance)
        {
            foreach (var item in m_Wrapper.m_SelectionActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SelectionActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SelectionActionActions @SelectionAction => new SelectionActionActions(this);
    public interface ISelectionActionActions
    {
        void OnSelectionControls(InputAction.CallbackContext context);
        void OnPointerPosition(InputAction.CallbackContext context);
    }
}
